### ISSUE TITLE
QAT-LIB (legacy) not Kernel 5.6+ compatible

### ISSUE THREAD

**Issue by Ornias1993** [intel/qatlib#1]
Currently the old ( < gen 4 ) RELEASE QAT lib is not compatible with recent kernels.
This is a problem.

This patch at least gets it into a somewhat workable (building) state:
https://raw.githubusercontent.com/spdk/spdk/master/test/common/config/pkgdep/patches/qat/0001-timespec.patch

**Comment by jdschuet** [comment]
Thanks for raising this issue.  Please note that this issue does not apply to QATlib.  The issue raised is associated with the kernel components of the QAT1.7 driver available on 01.org (https://01.org/intel-quickassist-technology).  The current version posted to 01.org (L.4.14.0-00031) includes the fix for this issue.
